# Tensors

The explanation of tensors through the [tutorial](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html), states that they are similair to matrices and arrays.
However they can run on GPU's, which significantly speeds up the computation process of machine learning.


In [1]:
# Getting started with the big imports
import torch
import numpy as np


## Initializing a Tensor

Different ways to initialize a tensor:

In [2]:
# Tensors (like numpy arrays) can be created directly from data.
# the data type is automatically infered (which is pretty STONKS)
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)


## From NUMPY arrays
np_array = np.array(data)
x_np = torch.from_numpy(np_array)


## From another Tensor
# and the new tensor retains both the datatype and shape of the previous tensor
x_ones = torch.ones_like(x_data) # retains the properties of the x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype = torch.float) # overrides the datatype
# of x_data
print(f"Random Tensors: \n {x_rand} \n")


## But also with random or constant values:
# Here these different Tensors has a set shape:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"zeros Tensor: \n {zeros_tensor} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensors: 
 tensor([[0.4462, 0.3486],
        [0.5292, 0.4667]]) 

Random Tensor: 
 tensor([[0.7362, 0.8798, 0.5979],
        [0.7320, 0.5044, 0.0348]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## Atributes of a Tensor
Here are some of the attributes of a Tensor:

In [3]:
tensor = torch.rand(3,4)

print(f"Shape of the Tensor: {tensor.shape}")
print(f"Datatype of the Tensor: {tensor.dtype}")
print(f"Device Tensor is stored on: {tensor.device}")



Shape of the Tensor: torch.Size([3, 4])
Datatype of the Tensor: torch.float32
Device Tensor is stored on: cpu


## Operations on Tensors

[Here](https://pytorch.org/docs/stable/torch.html) is the online documentation for the operations that can be performed on and with Tensors.
There are quite a lot, so it might be a good idea to have it saved.

Since all these operations can be run on the GPU (and usually much faster there), we would like to move our tensors to the GPU. This has to be done manually though.

In [4]:
# We move our tensors to the GPU if avaliable
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    

This Tensor API is very similair to how NumPy works.

Here are some example operations:

In [5]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[..., -1]}")     # This particular syntax was a bit weird to me..

tensor[:,-1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])


### Joining (concatanation)
Furthermore, Tensors can be joined by concatanation (I think concatanation might just be a different word for joining).

Here are some examples:

In [6]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)


tensor([[1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.]])


### Arithmetic Operations

Different arithmetic operations with Tensors (very informative I know)

In [7]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])

### Single-element tensors 

If you have a single value Tensor (one-element tensor), it can be converted into a Python numerical value using the `item()` operation:

In [8]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))


12.0 <class 'float'>


### In-Place operations

These are operations that overwrite the current object (tensor), instead of creating a new instance.
These operators are denoted by the `_` suffix.
Examples from the tutorial are:
`x.copy_(y)` and `x.t_()`, which will both change the value of `x`.

In [9]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]]) 

tensor([[6., 6., 6., 5.],
        [6., 6., 6., 5.],
        [6., 6., 6., 5.],
        [6., 6., 6., 5.]])


### Bridge with NumPy

Tensors on the CPU (I do not know whether this is restricted to the Tensors on the CPU or whether it is also a possibility for the Tensors on the GPU) and NumPy arrays can share their underlying memory locations, and changing one will change the other.

This is the problem/ nice attribute of having copies.

In [10]:
t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")


# A change in the Tensor is also reflected in the NumPy array
t.add_(1)
print("\nAfter addition of 1:")
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]

After addition of 1:
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


#### NumPy array to Tensor

It is the same the other way around

In [11]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"t: {t}")
print(f"n: {n}")

# And a change in one is still reflected in the other:
np.add(n, 1, out=n)
print("\nAfter addition of 1:")
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]

After addition of 1:
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
